In [1]:
import pandas as pd
import sqlalchemy
import pymysql
from sqlalchemy import create_engine

In [25]:
airlines = pd.read_csv('https://raw.githubusercontent.com/jpatokal/openflights/master/data/airlines.dat',
            header=None, sep=',', engine='python')

In [26]:
airlines = airlines.drop([0, 2, 3], axis =1)
airlines

,1,4,5,6,7
0,Unknown,NaN,\N,\N,Y
1,Private flight,NaN,NaN,NaN,Y
2,135 Airways,GNL,GENERAL,United States,N
3,1Time Airline,RNX,NEXTIME,South Africa,Y
4,2 Sqn No 1 Elementary Flying Training School,WYT,NaN,United Kingdom,N
5,213 Flight Unit,TFU,NaN,Russia,N
6,223 Flight Unit State Airline,CHD,CHKALOVSK-AVIA,Russia,N
7,224th Flight Unit,TTF,CARGO UNIT,Russia,N
8,247 Jet Ltd,TWF,CLOUD RUNNER,United Kingdom,N
9,3D Aviation,SEC,SECUREX,United States,N
10,40-Mile Air,MLA,MILE-AIR,United States,Y
11,4D Air,QRT,QUARTET,Thailand,N
12,611897 Alberta Limited,THD,DONUT,Canada,N
13,Ansett Australia,AAA,ANSETT,Australia,Y
14,Abacus International,NaN,NaN,Singapore,Y
15,Abelag Aviation,AAB,ABG,Belgium,N
16,Army Air Corps,AAC,ARMYAIR,United Kingdom,N
17,Aero Aviation Centre Ltd.,AAD,SUNRISE,Canada,N
18,Aero Servicios Ejecutivos Internacionales,SII,ASEISA,Mexico,N
19,Aero Biniza,BZS,BINIZA,Mexico,N
20,Aero Albatros,ABM,ALBATROS ESPANA,Spain,N
21,Aigle Azur,AAF,AIGLE AZUR,France,Y
22,Aloha Airlines,AAH,ALOHA,United States,Y
23,Alaska Island Air,AAK,ALASKA ISLAND,United States,N
24,American Airlines,AAL,AMERICAN,United States,Y
25,Aviation Management Corporation,AAM,AM CORP,United States,N
26,Atlantis Airlines (USA),AAO,ATLANTIS AIR,United States,N
27,Aerovista Airlines,AAP,AEROVISTA GROUP,United Arab Emirates,N
28,Asiana Airlines,AAR,ASIANA,Republic of Korea,Y
29,Askari Aviation,AAS,AL-AAS,Pakistan,Y
...,...,...,...,...,...
6132,Fly France,FRF,NaN,France,Y
6133,Jota Aviation,ENZ,ENZO,United Kingdom,Y
6134,Europe Jet,EU9,NaN,France,Y
6135,COBALT,FCB,COBALT,Cyprus,Y
6136,Southern Airways Express,LTD,LIGHTSPEED,United States,Y
6137,Deutsche Luftverkehrsgesellschaft (DLT),DWD,NaN,Germany,N
6138,Orenburzhie,ORG,NaN,Russia,Y
6139,Atlantic Air Cargo,\N,NaN,United States,N
6140,World Scale Airlines,WSS,NaN,United States,Y
6141,All America US,SSA,NaN,United States,Y
6142,University of Birmingham Air Squadron (RAF),UAY,UAY,United Kingdom,Y
6143,Choice Airways,CSX,NaN,United States,Y
6144,Aruba Airlines,ARU,NaN,Aruba,Y
6145,BudgetAir,BG1,NaN,Germany,Y
6146,Dynamic Airways,DYA,NaN,United States,Y
6147,Fly One,FI5,NaN,Moldova,Y
6148,Nordica,\N,REVAL,Estonia,Y
6149,Tez Jet Airlines,TEZ,NaN,Kyrgyzstan,Y
6150,Kush Air,KUH,NaN,South Sudan,Y
6151,Dummy,\N,NaN,France,N
6152,ViaAir,SRY,Stingray,United States,Y
6153,All America BOPY,PYB,BOPY,Paraguay,Y
6154,Thai Vietjet Air,TVJ,THAIVIET JET,Thailand,Y
6155,Air Andaman (2Y),AOW,AIR ANDAMAN,Thailand,N
6156,TDA Toa Domestic Airlines,TDA,Toa Domes,Japan,N
6157,GX Airlines,CBG,SPRAY,China,Y
6158,Lynx Aviation (L3/SSX),SSX,Shasta,United States,N
6159,Jetgo Australia,\N,NaN,Australia,Y
6160,Air Carnival,\N,NaN,India,Y
6161,Svyaz Rossiya,SJM,RussianConnecty,Russia,Y

In [27]:
airlines = airlines.drop([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [36]:
airlines = airlines[airlines[7] != "N"]

In [38]:
airlines_cleaned = airlines.reset_index(drop=True)
airlines_cleaned.rename(columns = {1: "airline_name", 4: "airline_ICAO", 5: "call_sign", 6: "country", 7:"active"})

,airline_name,airline_ICAO,call_sign,country,active
0,Ansett Australia,AAA,ANSETT,Australia,Y
1,Abacus International,NaN,NaN,Singapore,Y
2,Aigle Azur,AAF,AIGLE AZUR,France,Y
3,Aloha Airlines,AAH,ALOHA,United States,Y
4,American Airlines,AAL,AMERICAN,United States,Y
5,Asiana Airlines,AAR,ASIANA,Republic of Korea,Y
6,Askari Aviation,AAS,AL-AAS,Pakistan,Y
7,Afriqiyah Airways,AAW,AFRIQIYAH,Libya,Y
8,Allegiant Air,AAY,ALLEGIANT,United States,Y
9,Aban Air,ABE,ABAN,Iran,n
10,ABSA - Aerolinhas Brasileiras,TUS,ABSA Cargo,Brazil,Y
11,Astral Aviation,ACP,ASTRAL CARGO,Kenya,Y
12,Air Tindi,NaN,NaN,Canadian Territories,Y
13,Ada Air,ADE,ADA AIR,Albania,Y
14,Adria Airways,ADR,ADRIA,Slovenia,Y
15,Air Europa,AEA,EUROPA,Spain,Y
16,Aero Benin,AEB,AEROBEN,Benin,Y
17,Aegean Airlines,AEE,AEGEAN,Greece,Y
18,Air Europe,AEL,AIR EUROPE,Italy,Y
19,Alaska Central Express,AER,ACE AIR,United States,Y
20,ACES Colombia,AES,ACES,Colombia,Y
21,Astraeus,AEU,FLYSTAR,United Kingdom,Y
22,Aerosvit Airlines,AEW,AEROSVIT,Ukraine,Y
23,Air Italy,AEY,AIR ITALY,Italy,Y
24,Alliance Airlines,UTY,UNITY,Australia,Y
25,Ariana Afghan Airlines,AFG,ARIANA,Afghanistan,Y
26,Aeroflot Russian Airlines,AFL,AEROFLOT,Russia,Y
27,Air Bosna,BON,AIR BOSNA,Bosnia and Herzegovina,Y
28,Air France,AFR,AIRFRANS,France,Y
29,Air Caledonie International,ACI,AIRCALIN,France,Y
...,...,...,...,...,...
1222,Norwegian Air International (D8),IBK,NORTRANS,Norway,Y
1223,ATA Airlines (Iran),\N,ATALAR,Iran,Y
1224,VIA Líneas Aéreas,VIA,NaN,Argentina,Y
1225,GermanXL,GXG,NaN,Germany,Y
1226,Alghanim,KYA,NaN,United States,Y
1227,Indonesa Air Aisa X,IDX,Red Phoenix,Indonesia,Y
1228,Fly France,FRF,NaN,France,Y
1229,Jota Aviation,ENZ,ENZO,United Kingdom,Y
1230,Europe Jet,EU9,NaN,France,Y
1231,COBALT,FCB,COBALT,Cyprus,Y
1232,Southern Airways Express,LTD,LIGHTSPEED,United States,Y
1233,Orenburzhie,ORG,NaN,Russia,Y
1234,World Scale Airlines,WSS,NaN,United States,Y
1235,All America US,SSA,NaN,United States,Y
1236,University of Birmingham Air Squadron (RAF),UAY,UAY,United Kingdom,Y
1237,Choice Airways,CSX,NaN,United States,Y
1238,Aruba Airlines,ARU,NaN,Aruba,Y
1239,BudgetAir,BG1,NaN,Germany,Y
1240,Dynamic Airways,DYA,NaN,United States,Y
1241,Fly One,FI5,NaN,Moldova,Y
1242,Nordica,\N,REVAL,Estonia,Y
1243,Tez Jet Airlines,TEZ,NaN,Kyrgyzstan,Y
1244,Kush Air,KUH,NaN,South Sudan,Y
1245,ViaAir,SRY,Stingray,United States,Y
1246,All America BOPY,PYB,BOPY,Paraguay,Y
1247,Thai Vietjet Air,TVJ,THAIVIET JET,Thailand,Y
1248,GX Airlines,CBG,SPRAY,China,Y
1249,Jetgo Australia,\N,NaN,Australia,Y
1250,Air Carnival,\N,NaN,India,Y
1251,Svyaz Rossiya,SJM,RussianConnecty,Russia,Y